# Generated by Django 6.0.2 on 2026-02-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Experience in years', null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
